site_name: Graphene Django CRUDDALS

theme: readthedocs

plugins:
  - search
  - mkdocstrings

nav:
  
  - GET STARTED:
    -  🏁 Quick Start: GET STARTED/Quick-Start.md
    - ⚙️ Installation: GET STARTED/Installation.md
  
  - GUIDE TUTORIALS:
    -  💡 Basic Usage: GUIDE - TUTORIALS/Basic-Usage.md
    -  🎓 Advance Usage: GUIDE - TUTORIALS/Advance-Usage.md
    -  🌟 Features: GUIDE - TUTORIALS/Features.md

  - API:
    -  🛠️ Custom Types: API/Custom-Types.md

  






