site_name: Graphene Django CRUDDALS

theme: readthedocs

plugins:
  - search
  - mkdocstrings

nav:
  - Home: index.md
  - Basic Tutorial: basic-tutorial.md
  - What Can It Do?: what-can-do.md
  






