site_name: Graphene Django CRUDDALS

theme: readthedocs

plugins:
  - search
  - mkdocstrings

nav:
  - Quick start: index.md
  - Step-by-Step Installation: step-by-step-installation.md
  - What Can It Do?: what-can-do.md
  






