site_name: Graphene Django CRUDDALS
site_description: Graphene Django CRUDDALS Convert your Django models into a complete GraphQL API with all CRUD operations + DALS operations (Activate, Deactivate, List, Search)
theme:
  name: material
  logo: img/logoFullWhite.svg
  favicon: img/logoWhite.png
  language: en
  palette:
    - media: "(prefers-color-scheme)"
      primary: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      toggle:
        icon: material/brightness-auto
        name: Switch to system preference

repo_name: juanjcardona13/graphene_django_cruddals
repo_url: https://github.com/juanjcardona13/graphene_django_cruddals
edit_uri: tree/main/docs/docs
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [..]

extra:
  edit_on_github: true

extra_css:
  - css/extra.css

extra_javascript:
  - js/extra.js

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight
  - pymdownx.extra
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
      baselevel: 1
      separator: "-"

nav:
  - Home: index.md
  - GET STARTED:
    -  🏁 Quick Start: GET-STARTED/Quick-Start.md
    -  ⚙️ Installation: GET-STARTED/Installation.md

  - GUIDE TUTORIALS:
    -  💡 Basic Usage: GUIDE-TUTORIALS/Basic-Usage.md
    -  🎓 Advance Usage: GUIDE-TUTORIALS/Advance-Usage.md
    -  🌟 Features: GUIDE-TUTORIALS/Features.md

  - API REFERENCE:
    -  🛠️ Django Model : API-REFERENCE/django-model-cruddals.md
    -  🛠️ Django App : API-REFERENCE/django-app-cruddals.md
    -  🛠️ Django Project : API-REFERENCE/django-project-cruddals.md

docs_dir: docs

# readthedocs theme
# mkdocs